//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emajMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderDetail
    {
        public int OrderID { get; set; }
        public int StoreID { get; set; }
        public int Count { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Tbl_Order Tbl_Order { get; set; }
        public virtual Tbl_Store Tbl_Store { get; set; }
    }
}
